"""
Refresh the chart artefacts that the designed showcase page (docs/index.html)
references.

Outputs:
    docs/charts/donner_*.png   — static PNG copies (referenced by index.html)
    docs/charts/donner_*.html  — standalone interactive Plotly versions
                                 (linkable by direct URL for readers who want
                                 to explore)

Note: docs/index.html is hand-designed (via claude.ai/design) and is NOT
regenerated by this script. To rework the page itself, re-run the design pass
with claude.ai/design using design_brief.md + the four PNGs as inputs.

Usage:
    uv run python build_site.py
"""
from __future__ import annotations

import sys
from pathlib import Path

import chart as c

sys.stdout.reconfigure(line_buffering=True)

HERE = Path(__file__).parent
CHARTS_DIR = HERE / "docs" / "charts"
CHARTS_DIR.mkdir(parents=True, exist_ok=True)


def main() -> None:
    df = c.load("extracted_full.jsonl")
    print(f"loaded {len(df)} extractions")

    figs = {
        "choropleth": c.choropleth(df),
        "bar": c.bar_by_location(df, top_n=30),
        "countries": c.bar_by_country(df),
        "learned": c.bar_learned_from(df),
    }

    for name, fig in figs.items():
        png = CHARTS_DIR / f"donner_{name}.png"
        html = CHARTS_DIR / f"donner_{name}.html"
        # PNG dimensions: bar charts and the learned bar are wide; the
        # choropleth and country bar are closer to landscape ratios.
        width = 1400 if name in ("bar", "learned") else 1200
        fig.write_image(png, width=width, height=fig.layout.height or 720, scale=2)
        fig.write_html(html)
        print(f"  wrote charts/{png.name} + charts/{html.name}")

    print(f"\ndone. {len(figs)} chart pairs refreshed in {CHARTS_DIR.relative_to(HERE)}/")
    print("note: docs/index.html is hand-designed and was not modified.")


if __name__ == "__main__":
    main()
